GetMonData              = 0x0803FBE8 |1;
SetMonData              = 0x0804037C |1;
GetAbilityBySpecies     = 0x08040D38 |1;
Random                  = 0x08044EC8 |1;
__udivsi3               = 0x081E460C |1;
__umodsi3               = 0x081E4684 |1;

/* -------------------------------------------------------------------------- */

gBattlescriptCurrInstr  = 0x02023D74;
gPlayerParty            = 0x02024284;
